apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../function/k8scontrol-capd/cluster
  - ../../../../function/k8scontrol-capd/controlplane

patchesJson6902:
# Cluster
  - target:
      group: cluster.x-k8s.io
      version: v1alpha3
      kind: Cluster
      name: "${CLUSTER_NAME}"
    path: patch_cluster/cluster_name/cluster-patch-name.json

  - target:
      group: infrastructure.cluster.x-k8s.io
      version: v1alpha3
      kind: DockerCluster
      name: "${CLUSTER_NAME}"
    path: patch_cluster/cluster_name/dockercluster-patch-name.json

  - target:
      group: cluster.x-k8s.io
      version: v1alpha3
      kind: Cluster
      name: "${CLUSTER_NAME}"
    path: patch_cluster/cp_name/cluster-cp-ref.json

# Control Plane
  - target:
      group: controlplane.cluster.x-k8s.io
      version: v1alpha3
      kind: KubeadmControlPlane
      name: "${CLUSTER_NAME}-control-plane"
    path: patch_controlplane/machine_count.json

  - target:
      group: controlplane.cluster.x-k8s.io
      version: v1alpha3
      kind: KubeadmControlPlane
      name: "${CLUSTER_NAME}-control-plane"
    path: patch_controlplane/k8s_version.json

  - target:
      group: controlplane.cluster.x-k8s.io
      version: v1alpha3
      kind: KubeadmControlPlane
      name: "${CLUSTER_NAME}-control-plane"
    path: patch_controlplane/cp_name/kubeadmconfigtemplate-patch-name.json

  - target:
      group: infrastructure.cluster.x-k8s.io
      version: v1alpha3
      kind: DockerMachineTemplate
      name: "${CLUSTER_NAME}-control-plane"
    path: patch_controlplane/cp_name/dockermachinetemplate-patch-name.json

# Machine Health Check
  - target:
      group: cluster.x-k8s.io
      version: v1alpha3
      kind: MachineHealthCheck
      name: "${CLUSTER_NAME}-mhc-0"
    path: patch_mhc/machinehealthcheck-patch-clustername.json

  - target:
      group: cluster.x-k8s.io
      version: v1alpha3
      kind: MachineHealthCheck
      name: "${CLUSTER_NAME}-mhc-0"
    path: patch_mhc/machinehealthcheck-patch-mhcname.json
