apiVersion: kustomize.config.k8s.io/v1beta1
generatorOptions:
    disableNameSuffixHash: true
kind: Kustomization
resources:
- dtc.yaml
- ../../../../function/helm-controller
secretGenerator: []
patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: helm-operator
    namespace: flux
  patch: |-
    - op: remove
      path: /spec/template/spec/dnsConfig
    - op: remove
      path: /spec/template/spec/dnsPolicy
    - op: remove
      path: /spec/template/spec/nodeSelector
    - op: remove
      path: /spec/template/spec/tolerations
