privileged: true

image:
  repository: soelvkaer/vppcontainer
  tag: latest
  pullPolicy: IfNotPresent

volumeMounts:
  vpp_sockets:
    mountPath: /root/sockets

cnf:
  1:
    main_core: 8
    worker_cores: '12,38'
  2:
    main_core: 4 
    worker_cores: '5,6'

